const IANA_TIMEZONES = [
  {
    fullName: 'Niue Time',
    abbreviation: '-11',
    offsetVal: -660,
    offsetStr: '-11:00',
    IANA: 'Pacific/Niue',
  },
  {
    fullName: 'Samoa Standard Time',
    abbreviation: 'SST',
    offsetVal: -660,
    offsetStr: '-11:00',
    IANA: 'Pacific/Pago_Pago',
  },
  {
    fullName: 'Cook Islands Standard Time',
    abbreviation: '-10',
    offsetVal: -600,
    offsetStr: '-10:00',
    IANA: 'Pacific/Rarotonga',
  },
  {
    fullName: 'Hawaii-Aleutian Standard Time',
    abbreviation: 'HST',
    offsetVal: -600,
    offsetStr: '-10:00',
    IANA: 'America/Adak',
  },
  {
    fullName: 'Tahiti Time',
    abbreviation: '-10',
    offsetVal: -600,
    offsetStr: '-10:00',
    IANA: 'Pacific/Tahiti',
  },
  {
    fullName: 'Marquesas Time',
    abbreviation: '-0930',
    offsetVal: -570,
    offsetStr: '-09:30',
    IANA: 'Pacific/Marquesas',
  },
  {
    fullName: 'Alaska Standard Time',
    abbreviation: 'AKST',
    offsetVal: -540,
    offsetStr: '-09:00',
    IANA: 'America/Anchorage',
  },
  {
    fullName: 'Gambier Time',
    abbreviation: '-09',
    offsetVal: -540,
    offsetStr: '-09:00',
    IANA: 'Pacific/Gambier',
  },
  {
    fullName: 'Hawaii-Aleutian Daylight Time',
    abbreviation: 'HDT',
    offsetVal: -540,
    offsetStr: '-09:00',
    IANA: 'America/Adak',
  },
  {
    fullName: 'Alaska Daylight Time',
    abbreviation: 'AKDT',
    offsetVal: -480,
    offsetStr: '-08:00',
    IANA: 'America/Anchorage',
  },
  {
    fullName: 'Pacific Standard Time',
    abbreviation: 'PST',
    offsetVal: -480,
    offsetStr: '-08:00',
    IANA: 'America/Dawson',
  },
  {
    fullName: 'Pitcairn Time',
    abbreviation: '-08',
    offsetVal: -480,
    offsetStr: '-08:00',
    IANA: 'Pacific/Pitcairn',
  },
  {
    fullName: 'Mexican Pacific Standard Time',
    abbreviation: 'MST',
    offsetVal: -420,
    offsetStr: '-07:00',
    IANA: 'America/Chihuahua',
  },
  {
    fullName: 'Mountain Standard Time',
    abbreviation: 'MST',
    offsetVal: -420,
    offsetStr: '-07:00',
    IANA: 'America/Cambridge_Bay',
  },
  {
    fullName: 'Pacific Daylight Time',
    abbreviation: 'PDT',
    offsetVal: -420,
    offsetStr: '-07:00',
    IANA: 'America/Dawson',
  },
  {
    fullName: 'Central Standard Time',
    abbreviation: 'CST',
    offsetVal: -360,
    offsetStr: '-06:00',
    IANA: 'America/Belize',
  },
  {
    fullName: 'Easter Island Standard Time',
    abbreviation: '-06',
    offsetVal: -360,
    offsetStr: '-06:00',
    IANA: 'Pacific/Easter',
  },
  {
    fullName: 'Galapagos Time',
    abbreviation: '-06',
    offsetVal: -360,
    offsetStr: '-06:00',
    IANA: 'Pacific/Galapagos',
  },
  {
    fullName: 'Mexican Pacific Daylight Time',
    abbreviation: 'MDT',
    offsetVal: -360,
    offsetStr: '-06:00',
    IANA: 'America/Chihuahua',
  },
  {
    fullName: 'Mountain Daylight Time',
    abbreviation: 'MDT',
    offsetVal: -360,
    offsetStr: '-06:00',
    IANA: 'America/Cambridge_Bay',
  },
  {
    fullName: 'Acre Standard Time',
    abbreviation: '-05',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Eirunepe',
  },
  {
    fullName: 'Central Daylight Time',
    abbreviation: 'CDT',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Rankin_Inlet',
  },
  {
    fullName: 'Colombia Standard Time',
    abbreviation: '-05',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Bogota',
  },
  {
    fullName: 'Cuba Standard Time',
    abbreviation: 'CST',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Havana',
  },
  {
    fullName: 'Easter Island Summer Time',
    abbreviation: '-05',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'Pacific/Easter',
  },
  {
    fullName: 'Eastern Standard Time',
    abbreviation: 'EST',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Nassau',
  },
  {
    fullName: 'Ecuador Time',
    abbreviation: '-05',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Guayaquil',
  },
  {
    fullName: 'Peru Standard Time',
    abbreviation: '-05',
    offsetVal: -300,
    offsetStr: '-05:00',
    IANA: 'America/Lima',
  },
  {
    fullName: 'Amazon Standard Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Boa_Vista',
  },
  {
    fullName: 'Atlantic Standard Time',
    abbreviation: 'AST',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Antigua',
  },
  {
    fullName: 'Bolivia Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/La_Paz',
  },
  {
    fullName: 'Chile Standard Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Santiago',
  },
  {
    fullName: 'Cuba Daylight Time',
    abbreviation: 'CDT',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Havana',
  },
  {
    fullName: 'Eastern Daylight Time',
    abbreviation: 'EDT',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Nassau',
  },
  {
    fullName: 'Guyana Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Guyana',
  },
  {
    fullName: 'Paraguay Standard Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Asuncion',
  },
  {
    fullName: 'Venezuela Time',
    abbreviation: '-04',
    offsetVal: -240,
    offsetStr: '-04:00',
    IANA: 'America/Caracas',
  },
  {
    fullName: 'Newfoundland Standard Time',
    abbreviation: 'NST',
    offsetVal: -210,
    offsetStr: '-03:30',
    IANA: 'America/St_Johns',
  },
  {
    fullName: 'Argentina Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Argentina/Buenos_Aires',
  },
  {
    fullName: 'Atlantic Daylight Time',
    abbreviation: 'ADT',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'Atlantic/Bermuda',
  },
  {
    fullName: 'Brasilia Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Araguaina',
  },
  {
    fullName: 'Chile Summer Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Santiago',
  },
  {
    fullName: 'Falkland Islands Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'Atlantic/Stanley',
  },
  {
    fullName: 'French Guiana Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Cayenne',
  },
  {
    fullName: 'Paraguay Summer Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Asuncion',
  },
  {
    fullName: 'Rothera Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'Antarctica/Rothera',
  },
  {
    fullName: 'St. Pierre & Miquelon Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Miquelon',
  },
  {
    fullName: 'Suriname Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Paramaribo',
  },
  {
    fullName: 'Uruguay Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Montevideo',
  },
  {
    fullName: 'West Greenland Standard Time',
    abbreviation: '-03',
    offsetVal: -180,
    offsetStr: '-03:00',
    IANA: 'America/Nuuk',
  },
  {
    fullName: 'Newfoundland Daylight Time',
    abbreviation: 'NDT',
    offsetVal: -150,
    offsetStr: '-02:30',
    IANA: 'America/St_Johns',
  },
  {
    fullName: 'Fernando de Noronha Standard Time',
    abbreviation: '-02',
    offsetVal: -120,
    offsetStr: '-02:00',
    IANA: 'America/Noronha',
  },
  {
    fullName: 'South Georgia Time',
    abbreviation: '-02',
    offsetVal: -120,
    offsetStr: '-02:00',
    IANA: 'Atlantic/South_Georgia',
  },
  {
    fullName: 'St. Pierre & Miquelon Daylight Time',
    abbreviation: '-02',
    offsetVal: -120,
    offsetStr: '-02:00',
    IANA: 'America/Miquelon',
  },
  {
    fullName: 'West Greenland Summer Time',
    abbreviation: '-02',
    offsetVal: -120,
    offsetStr: '-02:00',
    IANA: 'America/Nuuk',
  },
  {
    fullName: 'Azores Standard Time',
    abbreviation: '-01',
    offsetVal: -60,
    offsetStr: '-01:00',
    IANA: 'Atlantic/Azores',
  },
  {
    fullName: 'Cape Verde Standard Time',
    abbreviation: '-01',
    offsetVal: -60,
    offsetStr: '-01:00',
    IANA: 'Atlantic/Cape_Verde',
  },
  {
    fullName: 'East Greenland Standard Time',
    abbreviation: '-01',
    offsetVal: -60,
    offsetStr: '-01:00',
    IANA: 'America/Scoresbysund',
  },
  {
    fullName: 'Azores Summer Time',
    abbreviation: '+00',
    offsetVal: 0,
    offsetStr: '+00:00',
    IANA: 'Atlantic/Azores',
  },
  {
    fullName: 'East Greenland Summer Time',
    abbreviation: '+00',
    offsetVal: 0,
    offsetStr: '+00:00',
    IANA: 'America/Scoresbysund',
  },
  {
    fullName: 'Greenwich Mean Time',
    abbreviation: 'GMT',
    offsetVal: 0,
    offsetStr: '+00:00',
    IANA: 'Antarctica/Troll',
  },
  {
    fullName: 'Western European Standard Time',
    abbreviation: 'WET',
    offsetVal: 0,
    offsetStr: '+00:00',
    IANA: 'Atlantic/Canary',
  },
  {
    fullName: 'British Summer Time',
    abbreviation: 'BST',
    offsetVal: 60,
    offsetStr: '+01:00',
    IANA: 'Europe/London',
  },
  {
    fullName: 'Central European Standard Time',
    abbreviation: 'CET',
    offsetVal: 60,
    offsetStr: '+01:00',
    IANA: 'Europe/Andorra',
  },
  {
    fullName: 'Irish Standard Time',
    abbreviation: 'IST',
    offsetVal: 60,
    offsetStr: '+01:00',
    IANA: 'Europe/Dublin',
  },
  {
    fullName: 'West Africa Standard Time',
    abbreviation: 'WAT',
    offsetVal: 60,
    offsetStr: '+01:00',
    IANA: 'Africa/Lagos',
  },
  {
    fullName: 'Western European Summer Time',
    abbreviation: 'WEST',
    offsetVal: 60,
    offsetStr: '+01:00',
    IANA: 'Atlantic/Canary',
  },
  {
    fullName: 'Central Africa Time',
    abbreviation: 'CAT',
    offsetVal: 120,
    offsetStr: '+02:00',
    IANA: 'Africa/Bujumbura',
  },
  {
    fullName: 'Central European Summer Time',
    abbreviation: 'CEST',
    offsetVal: 120,
    offsetStr: '+02:00',
    IANA: 'Europe/Andorra',
  },
  {
    fullName: 'Eastern European Standard Time',
    abbreviation: 'EET',
    offsetVal: 120,
    offsetStr: '+02:00',
    IANA: 'Europe/Helsinki',
  },
  {
    fullName: 'Israel Standard Time',
    abbreviation: 'IST',
    offsetVal: 120,
    offsetStr: '+02:00',
    IANA: 'Asia/Jerusalem',
  },
  {
    fullName: 'South Africa Standard Time',
    abbreviation: 'SAST',
    offsetVal: 120,
    offsetStr: '+02:00',
    IANA: 'Africa/Johannesburg',
  },
  {
    fullName: 'Arabian Standard Time',
    abbreviation: '+03',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Asia/Riyadh',
  },
  {
    fullName: 'East Africa Time',
    abbreviation: 'EAT',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Africa/Djibouti',
  },
  {
    fullName: 'Eastern European Summer Time',
    abbreviation: 'EEST',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Europe/Helsinki',
  },
  {
    fullName: 'Israel Daylight Time',
    abbreviation: 'IDT',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Asia/Jerusalem',
  },
  {
    fullName: 'Moscow Standard Time',
    abbreviation: '+03',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Europe/Minsk',
  },
  {
    fullName: 'Syowa Time',
    abbreviation: '+03',
    offsetVal: 180,
    offsetStr: '+03:00',
    IANA: 'Antarctica/Syowa',
  },
  {
    fullName: 'Iran Standard Time',
    abbreviation: '+0330',
    offsetVal: 210,
    offsetStr: '+03:30',
    IANA: 'Asia/Tehran',
  },
  {
    fullName: 'Armenia Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Asia/Yerevan',
  },
  {
    fullName: 'Azerbaijan Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Asia/Baku',
  },
  {
    fullName: 'Georgia Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Asia/Tbilisi',
  },
  {
    fullName: 'Gulf Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Asia/Dubai',
  },
  {
    fullName: 'Mauritius Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Indian/Mauritius',
  },
  {
    fullName: 'Réunion Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Indian/Reunion',
  },
  {
    fullName: 'Samara Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Europe/Samara',
  },
  {
    fullName: 'Seychelles Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Indian/Mahe',
  },
  {
    fullName: 'Volgograd Standard Time',
    abbreviation: '+04',
    offsetVal: 240,
    offsetStr: '+04:00',
    IANA: 'Europe/Volgograd',
  },
  {
    fullName: 'Afghanistan Time',
    abbreviation: '+0430',
    offsetVal: 270,
    offsetStr: '+04:30',
    IANA: 'Asia/Kabul',
  },
  {
    fullName: 'Iran Daylight Time',
    abbreviation: '+0430',
    offsetVal: 270,
    offsetStr: '+04:30',
    IANA: 'Asia/Tehran',
  },
  {
    fullName: 'French Southern & Antarctic Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Indian/Kerguelen',
  },
  {
    fullName: 'Maldives Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Indian/Maldives',
  },
  {
    fullName: 'Mawson Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Antarctica/Mawson',
  },
  {
    fullName: 'Pakistan Standard Time',
    abbreviation: 'PKT',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Karachi',
  },
  {
    fullName: 'Tajikistan Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Dushanbe',
  },
  {
    fullName: 'Turkmenistan Standard Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Ashgabat',
  },
  {
    fullName: 'Uzbekistan Standard Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Samarkand',
  },
  {
    fullName: 'West Kazakhstan Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Aqtau',
  },
  {
    fullName: 'Yekaterinburg Standard Time',
    abbreviation: '+05',
    offsetVal: 300,
    offsetStr: '+05:00',
    IANA: 'Asia/Yekaterinburg',
  },
  {
    fullName: 'India Standard Time',
    abbreviation: 'IST',
    offsetVal: 330,
    offsetStr: '+05:30',
    IANA: 'Asia/Kolkata',
  },
  {
    fullName: 'Nepal Time',
    abbreviation: '+0545',
    offsetVal: 345,
    offsetStr: '+05:45',
    IANA: 'Asia/Kathmandu',
  },
  {
    fullName: 'Bangladesh Standard Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Asia/Dhaka',
  },
  {
    fullName: 'Bhutan Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Asia/Thimphu',
  },
  {
    fullName: 'East Kazakhstan Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Asia/Almaty',
  },
  {
    fullName: 'Indian Ocean Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Indian/Chagos',
  },
  {
    fullName: 'Kyrgyzstan Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Asia/Bishkek',
  },
  {
    fullName: 'Omsk Standard Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Asia/Omsk',
  },
  {
    fullName: 'Vostok Time',
    abbreviation: '+06',
    offsetVal: 360,
    offsetStr: '+06:00',
    IANA: 'Antarctica/Vostok',
  },
  {
    fullName: 'Cocos Islands Time',
    abbreviation: '+0630',
    offsetVal: 390,
    offsetStr: '+06:30',
    IANA: 'Indian/Cocos',
  },
  {
    fullName: 'Myanmar Time',
    abbreviation: '+0630',
    offsetVal: 390,
    offsetStr: '+06:30',
    IANA: 'Asia/Yangon',
  },
  {
    fullName: 'Christmas Island Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Indian/Christmas',
  },
  {
    fullName: 'Davis Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Antarctica/Davis',
  },
  {
    fullName: 'Hovd Standard Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Asia/Hovd',
  },
  {
    fullName: 'Indochina Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Asia/Bangkok',
  },
  {
    fullName: 'Krasnoyarsk Standard Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Asia/Krasnoyarsk',
  },
  {
    fullName: 'Novosibirsk Standard Time',
    abbreviation: '+07',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Asia/Novosibirsk',
  },
  {
    fullName: 'Western Indonesia Time',
    abbreviation: 'WIB',
    offsetVal: 420,
    offsetStr: '+07:00',
    IANA: 'Asia/Jakarta',
  },
  {
    fullName: 'Australian Western Standard Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Antarctica/Casey',
  },
  {
    fullName: 'Brunei Darussalam Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Brunei',
  },
  {
    fullName: 'Central Indonesia Time',
    abbreviation: 'WITA',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Makassar',
  },
  {
    fullName: 'China Standard Time',
    abbreviation: 'CST',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Shanghai',
  },
  {
    fullName: 'Hong Kong Standard Time',
    abbreviation: 'HKT',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Hong_Kong',
  },
  {
    fullName: 'Irkutsk Standard Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Irkutsk',
  },
  {
    fullName: 'Malaysia Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Kuching',
  },
  {
    fullName: 'Philippine Standard Time',
    abbreviation: 'PST',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Manila',
  },
  {
    fullName: 'Singapore Standard Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Singapore',
  },
  {
    fullName: 'Taipei Standard Time',
    abbreviation: 'CST',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Taipei',
  },
  {
    fullName: 'Ulaanbaatar Standard Time',
    abbreviation: '+08',
    offsetVal: 480,
    offsetStr: '+08:00',
    IANA: 'Asia/Choibalsan',
  },
  {
    fullName: 'Australian Central Western Standard Time',
    abbreviation: '+0845',
    offsetVal: 525,
    offsetStr: '+08:45',
    IANA: 'Australia/Eucla',
  },
  {
    fullName: 'East Timor Time',
    abbreviation: '+09',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Asia/Dili',
  },
  {
    fullName: 'Eastern Indonesia Time',
    abbreviation: 'WIT',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Asia/Jayapura',
  },
  {
    fullName: 'Japan Standard Time',
    abbreviation: 'JST',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Asia/Tokyo',
  },
  {
    fullName: 'Korean Standard Time',
    abbreviation: 'KST',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Asia/Pyongyang',
  },
  {
    fullName: 'Palau Time',
    abbreviation: '+09',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Pacific/Palau',
  },
  {
    fullName: 'Yakutsk Standard Time',
    abbreviation: '+09',
    offsetVal: 540,
    offsetStr: '+09:00',
    IANA: 'Asia/Chita',
  },
  {
    fullName: 'Australian Central Standard Time',
    abbreviation: 'ACST',
    offsetVal: 570,
    offsetStr: '+09:30',
    IANA: 'Australia/Adelaide',
  },
  {
    fullName: 'Australian Eastern Standard Time',
    abbreviation: 'AEST',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Antarctica/Macquarie',
  },
  {
    fullName: 'Chamorro Standard Time',
    abbreviation: 'ChST',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Pacific/Guam',
  },
  {
    fullName: 'Chuuk Time',
    abbreviation: '+10',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Pacific/Chuuk',
  },
  {
    fullName: 'Dumont-d’Urville Time',
    abbreviation: '+10',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Antarctica/DumontDUrville',
  },
  {
    fullName: 'Papua New Guinea Time',
    abbreviation: '+10',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Pacific/Port_Moresby',
  },
  {
    fullName: 'Vladivostok Standard Time',
    abbreviation: '+10',
    offsetVal: 600,
    offsetStr: '+10:00',
    IANA: 'Asia/Ust-Nera',
  },
  {
    fullName: 'Australian Central Daylight Time',
    abbreviation: 'ACDT',
    offsetVal: 630,
    offsetStr: '+10:30',
    IANA: 'Australia/Adelaide',
  },
  {
    fullName: 'Lord Howe Standard Time',
    abbreviation: '+1030',
    offsetVal: 630,
    offsetStr: '+10:30',
    IANA: 'Australia/Lord_Howe',
  },
  {
    fullName: 'Australian Eastern Daylight Time',
    abbreviation: 'AEDT',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Antarctica/Macquarie',
  },
  {
    fullName: 'Casey Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Antarctica/Casey',
  },
  {
    fullName: 'Kosrae Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Kosrae',
  },
  {
    fullName: 'Lord Howe Daylight Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Australia/Lord_Howe',
  },
  {
    fullName: 'Magadan Standard Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Asia/Magadan',
  },
  {
    fullName: 'New Caledonia Standard Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Noumea',
  },
  {
    fullName: 'Norfolk Island Standard Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Norfolk',
  },
  {
    fullName: 'Ponape Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Pohnpei',
  },
  {
    fullName: 'Sakhalin Standard Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Asia/Sakhalin',
  },
  {
    fullName: 'Solomon Islands Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Guadalcanal',
  },
  {
    fullName: 'Vanuatu Standard Time',
    abbreviation: '+11',
    offsetVal: 660,
    offsetStr: '+11:00',
    IANA: 'Pacific/Efate',
  },
  {
    fullName: 'Anadyr Standard Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Asia/Anadyr',
  },
  {
    fullName: 'Fiji Standard Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Fiji',
  },
  {
    fullName: 'Gilbert Islands Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Tarawa',
  },
  {
    fullName: 'Marshall Islands Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Kwajalein',
  },
  {
    fullName: 'Nauru Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Nauru',
  },
  {
    fullName: 'New Zealand Standard Time',
    abbreviation: 'NZST',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Antarctica/McMurdo',
  },
  {
    fullName: 'Norfolk Island Daylight Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Norfolk',
  },
  {
    fullName: 'Petropavlovsk-Kamchatski Standard Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Asia/Kamchatka',
  },
  {
    fullName: 'Tuvalu Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Funafuti',
  },
  {
    fullName: 'Wake Island Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Wake',
  },
  {
    fullName: 'Wallis & Futuna Time',
    abbreviation: '+12',
    offsetVal: 720,
    offsetStr: '+12:00',
    IANA: 'Pacific/Wallis',
  },
  {
    fullName: 'Chatham Standard Time',
    abbreviation: '+1245',
    offsetVal: 765,
    offsetStr: '+12:45',
    IANA: 'Pacific/Chatham',
  },
  {
    fullName: 'Apia Standard Time',
    abbreviation: '+13',
    offsetVal: 780,
    offsetStr: '+13:00',
    IANA: 'Pacific/Apia',
  },
  {
    fullName: 'New Zealand Daylight Time',
    abbreviation: 'NZDT',
    offsetVal: 780,
    offsetStr: '+13:00',
    IANA: 'Antarctica/McMurdo',
  },
  {
    fullName: 'Phoenix Islands Time',
    abbreviation: '+13',
    offsetVal: 780,
    offsetStr: '+13:00',
    IANA: 'Pacific/Kanton',
  },
  {
    fullName: 'Tokelau Time',
    abbreviation: '+13',
    offsetVal: 780,
    offsetStr: '+13:00',
    IANA: 'Pacific/Fakaofo',
  },
  {
    fullName: 'Tonga Standard Time',
    abbreviation: '+13',
    offsetVal: 780,
    offsetStr: '+13:00',
    IANA: 'Pacific/Tongatapu',
  },
  {
    fullName: 'Chatham Daylight Time',
    abbreviation: '+1345',
    offsetVal: 825,
    offsetStr: '+13:45',
    IANA: 'Pacific/Chatham',
  },
  {
    fullName: 'Apia Daylight Time',
    abbreviation: '+14',
    offsetVal: 840,
    offsetStr: '+14:00',
    IANA: 'Pacific/Apia',
  },
  {
    fullName: 'Line Islands Time',
    abbreviation: '+14',
    offsetVal: 840,
    offsetStr: '+14:00',
    IANA: 'Pacific/Kiritimati',
  },
]
